# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://francescorner.github.io
title: Frances Corner Gardens
email: frances.corner@gmail.com
author: Frances Corner
description: > # "Write an awesome description for your new site here. 
  Reliable, friendly and creative gardening services from a passionate gardener.
  Covering the Richmond, Kew, Twickenham and Kingston area.
copyright: 'Copyright &copy; 2019 Frances Corner. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/fcorner
  - title: email
    url: mailto:frances.corner@gmail.com
    fa-icon: envelope
